### ISSUE TITLE
Artifacts from https://androidx.dev/storage/compose-compiler/repository/ are not accessible

### ISSUE THREAD

**Issue by baole** [jimgoog/ComposeAppUsingPrereleaseComposeCompiler#1]
As of today, artifacts from https://androidx.dev/storage/compose-compiler/repository/ are not accessible

**Comment by jimgoog** [comment]
cc @tikurahul

**Comment by jimgoog** [comment]
Looks like the trailing slash on the index page is creating an issue.

I submitted a fix, waiting for code review and for that fix to get merged.  In the mean time, use the URL https://androidx.dev/storage/compose-compiler/repository instead if manually fetching/clicking jars.

**Comment by baole** [comment]
@jimgoog I'm using Compose version `1.2.0-dev-k1.7.0-53370d83bb1` (listed on https://androidx.dev/storage/compose-compiler/repository/). It still doesn't work with following errors

```
   > Could not find androidx.compose.runtime:runtime:1.2.0-dev-k1.7.0-53370d83bb1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/compose/runtime/runtime/1.2.0-dev-k1.7.0-53370d83bb1/runtime-1.2.0-dev-k1.7.0-53370d83bb1.pom
       - https://repo.maven.apache.org/maven2/androidx/compose/runtime/runtime/1.2.0-dev-k1.7.0-53370d83bb1/runtime-1.2.0-dev-k1.7.0-53370d83bb1.pom
       - https://androidx.dev/storage/compose-compiler/repository/androidx/compose/runtime/runtime/1.2.0-dev-k1.7.0-53370d83bb1/runtime-1.2.0-dev-k1.7.0-53370d83bb1.pom
       - https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev/androidx/compose/runtime/runtime/1.2.0-dev-k1.7.0-53370d83bb1/runtime-1.2.0-dev-k1.7.0-53370d83bb1.pom
     Required by:

```

**Comment by jimgoog** [comment]
Looks like the bug is back, digging now

**Comment by jimgoog** [comment]
The artifact being requested is `androidx.compose.runtime:runtime` version `1.2.0-dev-k1.7.0-53370d83bb1`.

The only dependency you should be upgrading to `1.2.0-dev-k1.7.0-53370d83bb1` is the compiler artifact by setting `kotlinCompilerExtensionVersion` as per https://github.com/jimgoog/ComposeAppUsingPrereleaseComposeCompiler/blob/main/app/build.gradle#L39

You should not be setting the version to `1.2.0-dev-k1.7.0-53370d83bb1` for any other compose libraries/dependencies.
