### ISSUE TITLE
Missing pre Kotlin 2.0.0 targets in Compatibility table

### ISSUE THREAD

**Issue by GuilhE** [jimgoog/ComposeAppUsingPrereleaseComposeCompiler#6]
[Compatibility table](https://androidx.dev/storage/compose-compiler/repository) only shows values for `2.0.0-Beta1` and beyond, what happen to older versions?

**Comment by jimgoog** [comment]
The `androidx.dev` builds were intended for testing / development / living on the edge.  They were intended for pre-flight testing new versions of Kotlin, and were never intended for production use.  We couldn't think of any practical reason why someone should need those builds for pre-releases (eg. `-BetaXX` or `-RC`) after the stable version of that release has been published.  For this reason, we removed them.

If you have a compelling reason/need for them to exist, please elaborate, and we could potentially reconsider.

Keep in mind that for stable builds of Kotlin, you can see all the corresponding stable releases of compose-compiler here: https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility
